#!/bin/sh
set -e

ln -sf "$PWD/.bashrc" "$HOME/.bashrc"
ln -sf "$PWD/.profile" "$HOME/.profile"
ln -sf "$PWD/.profile" "$HOME/.bash_profile"
ln -sf "$PWD/.tmux.conf" "$HOME/.tmux.conf"
ln -sf "$PWD/scripts" "$HOME/Scripts"
ln -sf "$PWD/.gitconfig" "$HOME/.gitconfig"
ln -sf "$PWD/.gitignore" "$HOME/.gitignore"
ln -sf "$PWD/.gitmessage" "$HOME/.gitmessage"
ln -sf "$PWD/.Xresources" "$HOME/.Xresources"
# ln -sf "$PWD/.gitattributes" "$HOME/.gitattributes"

for i in nvim i3 i3status lynx dunst rofi; do
  cd $i && ./setup
  cd -
done
