#!/bin/sh

ln -sf "$PWD/config" "$HOME/.config/i3/config"
ln -sf "$PWD/workspace-dev.json" "$HOME/.config/i3/workspace-dev.json"
ln -sf "$PWD/workspace-term.json" "$HOME/.config/i3/workspace-term.json"
