#!/bin/bash

TOO_LOW=10
DISPLAY=${DISPLAY-:0}
IFS=" " read -r -a battery <<< "$(acpi -b | grep -m 1 -P -o '\w+, [0-9]+(?=%)' | tr -d ,)"

if [ "${battery[1]}" -le "$TOO_LOW" ] && \
				[ "${battery[0]}" = "Discharging" ]
then
    notify -u critical -t 3000 "Battery low" "Battery level is ${battery[1]}%!"
fi

exit 0
