#!/bin/bash

if [[ -n $1 ]]; then
				DIRNAME=$1
else
				DIRNAME=${PWD##*/}
fi;

composer -q install > /dev/null 2>&1
composer -q install --no-dev
if [[ -f "$DIRNAME.zip" ]]; then rm "$DIRNAME.zip"; fi;
if [[ -f "package.json" ]]; then npm run prod > /dev/null 2>&1; fi;
composer archive --file="$DIRNAME" --format=zip
composer -q install > /dev/null 2>&1
