#!/bin/sh

MODE="$1"
ROTATION="${2:-'normal'}"
INTERNAL_MONITOR="eDP-1"
EXTERN_MONITOR="HDMI-1"

case $MODE in
  on)
    xrandr --output "$EXTERN_MONITOR" --auto \
      --right-of "$INTERNAL_MONITOR" \
      --rotate "$ROTATION"
    [ -f "$HOME/.fehbg" ] && exec "$HOME/.fehbg"
    ;;
  off)
    xrandr --output "$EXTERN_MONITOR" --off
    ;;
esac
