#!/usr/bin/bash

if type notify-send >/dev/null 2>&1; then
  COMMAND=notify-send
elif type dunstify >/dev/null 2>&1; then
  COMMAND=dunstify
else
  echo 'No notification command.'
  exit 1
fi;

exec $COMMAND $@
