#!/bin/bash
function encode() {
  python3 -c "import urllib.parse; print(urllib.parse.quote(input()))" <<< "$1"
}

query=$(encode "$*")

lynx "https://lite.duckduckgo.com/lite?q=$query"
# lynx "https://lite.qwant.com/?q=$query"
