#!/bin/bash

set -eu

ZET="$HOME/Repos/exobrain"

_isosec() {
  date -u +%Y%m%d%H%M%S
}

note() {
  category="${1:-drafts}"

  [[ ! -d "$ZET/$category" ]] && mkdir "$ZET/$category"
  file="$ZET/$category/$(_isosec).md"
  touch "$file"
  "$EDITOR" "$file"
}

_git() {
  git -C "$ZET" "$@"
}

case "$1" in
  note)
    shift
    note "$@"
  ;;
  git)
    shift
    _git "$@"
  ;;
esac

exit 0
